### ISSUE TITLE
Sound: why alsa and not pulseaudio?

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#35]
Why did you decided to stick with alsa instead of pulseaudio?

I've been using pulseaudio for a long time and don't see any significant troubles (except for necessity of restarting pulse after some suspending of my laptop).

[Benefits](https://en.wikipedia.org/wiki/Pulse_Audio#Features) (short list): Bluetooth audio support, network audio support, per application volume control, simplified volume controls and source selection.

**Comment by pigmonkey** [comment]
I was turned off from pulse audio a long time ago due to the difficulty of setup. This was a decade ago, so I'm sure things are different now. I do appreciate that alsa is basically just plug-and-play, but pulse is something we should think about since we should be able to automate away any remaining headache in the setup. It makes sense if just to support bluetooth audio.

**Comment by pigmonkey** [comment]
There's a branch with pulse stuff that I've been using for a week or so. I want to look at bluetooth audio before merging it in.

**Comment by pigmonkey** [comment]
Pulse and bluetooth audio are in master.
