### ISSUE TITLE
SSH: option to generate ssh private key for user

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#37]
Probably it is sensible to generate ssh private key if it isn't set.

With code like this:
```
 63 - name: Generate user SSH key
 64   user:
 65     name: "{{ user.name }}"
 66     generate_ssh_key: yes
 67     ssh_key_bits: 2048
 68     ssh_key_file: "/home/{{ user.name }}/.ssh/id_rsa"
 69   when: ssh.user_key is undefined
```

**Comment by pigmonkey** [comment]
The only reason the user needs to define their SSH key in the config is to clone their. If they have a key, but aren't using the dotfiles role (because they don't keep those files in git, for instance), I don't think I want to generate a key for them. I wouldn't want to generate GPG or Tarsnap keys for users either.

Key management is important. I think it is probably better for users to explicitly create keys when they need them.
