### ISSUE TITLE
Why do you have both isync and offlineimap installed?

### ISSUE THREAD

**Issue by petRUShka** [pigmonkey/spark#46]
There are at least to mail syncing tools: isync and offlineimap:

https://github.com/pigmonkey/spark/blob/master/roles/mail/tasks/main.yml

Why do you need both of them?

**Comment by pigmonkey** [comment]
Because we support both.

See the Receiving Mail section of the README.

**Comment by petRUShka** [comment]
Could you please put your 50 cents and explain what do you prefer more and why?

**Comment by pigmonkey** [comment]
They're both equally annoying.

OfflineIMAP crashes occasionally, particularly if you run it as a daemon. I've never had isync crash, but it does occasionally take a long time to sync for unexplained reasons. OfflineIMAP is mostly abandoned by the core developers, but still has a decent community around it. isync does not have any official notice of abandonment but hasn't had a release since 2015, for whatever that's worth.

Both generally get the job done. I've never had either delete mail or anything like that. Because we run the tools in a timer the annoyances of both are generally hidden from the user.

[imapfw](https://github.com/OfflineIMAP/imapfw) will apparently be the solution to all of our woes once it gets a stable release.

**Comment by petRUShka** [comment]
Thanks for explaining your experience .

BTW, it looks like isync developer make a commit from time to time till now: https://sourceforge.net/p/isync/isync/ci/77acc268123b8233843ca9bc3dcf90669efde08f/log/?path=
