### ISSUE TITLE
ttf-impallari-cantora font cannot be downloaded

### ISSUE THREAD

**Issue by elvetemedve** [pigmonkey/spark#77]
## The problem

Installation of the [ttf-impallari-cantora](https://aur.archlinux.org/packages/ttf-impallari-cantora/) package failed, because the font cannot be downloaded from the source URL. See below.
![screenshot from 2018-04-04 23-48-01](https://user-images.githubusercontent.com/596431/38336612-aa782f9c-3862-11e8-8ea5-f35d5c43a870.png)

### Expected behaviour

I would expect to be able to define the list of fonts to be installed by myself (like how it's done with [AUR packages](https://github.com/pigmonkey/spark/blob/master/group_vars/all#L20-L26).), but it's [hard-coded](https://github.com/pigmonkey/spark/blob/master/roles/fonts/tasks/main.yml#L29-L57) currently.

**Comment by pigmonkey** [comment]
This role was rebuilt when the Infinality repository went away, with the goal of replacing the behaviour that Infinality had previously provided: nice looking fonts with no effort. We could move the core fonts and AUR fonts to configurable variables. I have not done that previously because fonts are close to the last thing I want to thing about on my machine. I didn't think other people would want to configure fonts.

**Comment by elvetemedve** [comment]
I liked the Infinality bundle fonts, what a pity that it's gone.

I agree that people generally want good looking fonts and won't bother with custom fonts. However there are few cases when you need a specific font. In my case I use [Oh My Zsh](http://ohmyz.sh/) configuration for shell which needs [Powerline patched font](https://github.com/powerline/fonts). I could install it manually later, but I would prefer to tell Ansible to do it.
